version: "3.9"

services:
  iris:
    image: ghcr.io/notataxpayer/iris-predict:dev
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    environment:
       - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI:-}
       - DVC_NO_PULL=${DVC_NO_PULL:-false}
    volumes:
      - ./artifacts:/app/artifacts
      - ./mlruns:/app/mlruns
      - ./metrics:/app/metrics 
    ports:
      - "5000:5000"
    command: ["python","iris_classification.py","--csv","iris.csv"]
